version: '3.7'
services:
    server:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend/:/backend/
            - ./dev_cache/site-packages:/dev_cache/site-packages
        command:
            sh -c "cp -r /usr/local/lib/python3.9/site-packages/* /dev_cache/site-packages/  &&
            uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000"
        ports:
            - 8000:8000
